/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as AuthenticatedLearningCentersRouteImport } from './routes/_authenticated/learning-centers'
import { Route as AuthenticatedTestsTestsRouteImport } from './routes/_authenticated/tests/tests'
import { Route as AuthenticatedTestsQuestionsRouteImport } from './routes/_authenticated/tests/questions'
import { Route as AuthenticatedTestsModulesRouteImport } from './routes/_authenticated/tests/modules'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedContentWordsRouteImport } from './routes/_authenticated/content/words'
import { Route as AuthenticatedContentLessonsRouteImport } from './routes/_authenticated/content/lessons'
import { Route as AuthenticatedContentCoursesRouteImport } from './routes/_authenticated/content/courses'
import { Route as AuthenticatedTestsQuestionsCreateRouteImport } from './routes/_authenticated/tests/questions/create'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLearningCentersRoute =
  AuthenticatedLearningCentersRouteImport.update({
    id: '/learning-centers',
    path: '/learning-centers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsTestsRoute = AuthenticatedTestsTestsRouteImport.update({
  id: '/tests/tests',
  path: '/tests/tests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTestsQuestionsRoute =
  AuthenticatedTestsQuestionsRouteImport.update({
    id: '/tests/questions',
    path: '/tests/questions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsModulesRoute =
  AuthenticatedTestsModulesRouteImport.update({
    id: '/tests/modules',
    path: '/tests/modules',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentWordsRoute =
  AuthenticatedContentWordsRouteImport.update({
    id: '/content/words',
    path: '/content/words',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentLessonsRoute =
  AuthenticatedContentLessonsRouteImport.update({
    id: '/content/lessons',
    path: '/content/lessons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContentCoursesRoute =
  AuthenticatedContentCoursesRouteImport.update({
    id: '/content/courses',
    path: '/content/courses',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTestsQuestionsCreateRoute =
  AuthenticatedTestsQuestionsCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => AuthenticatedTestsQuestionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/content/courses': typeof AuthenticatedContentCoursesRoute
  '/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/content/words': typeof AuthenticatedContentWordsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/tests/modules': typeof AuthenticatedTestsModulesRoute
  '/tests/questions': typeof AuthenticatedTestsQuestionsRouteWithChildren
  '/tests/tests': typeof AuthenticatedTestsTestsRoute
  '/tests/questions/create': typeof AuthenticatedTestsQuestionsCreateRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/': typeof AuthenticatedIndexRoute
  '/content/courses': typeof AuthenticatedContentCoursesRoute
  '/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/content/words': typeof AuthenticatedContentWordsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/tests/modules': typeof AuthenticatedTestsModulesRoute
  '/tests/questions': typeof AuthenticatedTestsQuestionsRouteWithChildren
  '/tests/tests': typeof AuthenticatedTestsTestsRoute
  '/tests/questions/create': typeof AuthenticatedTestsQuestionsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/learning-centers': typeof AuthenticatedLearningCentersRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/content/courses': typeof AuthenticatedContentCoursesRoute
  '/_authenticated/content/lessons': typeof AuthenticatedContentLessonsRoute
  '/_authenticated/content/words': typeof AuthenticatedContentWordsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/tests/modules': typeof AuthenticatedTestsModulesRoute
  '/_authenticated/tests/questions': typeof AuthenticatedTestsQuestionsRouteWithChildren
  '/_authenticated/tests/tests': typeof AuthenticatedTestsTestsRoute
  '/_authenticated/tests/questions/create': typeof AuthenticatedTestsQuestionsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/learning-centers'
    | '/user-management'
    | '/'
    | '/content/courses'
    | '/content/lessons'
    | '/content/words'
    | '/errors/$error'
    | '/tests/modules'
    | '/tests/questions'
    | '/tests/tests'
    | '/tests/questions/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/learning-centers'
    | '/user-management'
    | '/'
    | '/content/courses'
    | '/content/lessons'
    | '/content/words'
    | '/errors/$error'
    | '/tests/modules'
    | '/tests/questions'
    | '/tests/tests'
    | '/tests/questions/create'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/learning-centers'
    | '/_authenticated/user-management'
    | '/_authenticated/'
    | '/_authenticated/content/courses'
    | '/_authenticated/content/lessons'
    | '/_authenticated/content/words'
    | '/_authenticated/errors/$error'
    | '/_authenticated/tests/modules'
    | '/_authenticated/tests/questions'
    | '/_authenticated/tests/tests'
    | '/_authenticated/tests/questions/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/learning-centers': {
      id: '/_authenticated/learning-centers'
      path: '/learning-centers'
      fullPath: '/learning-centers'
      preLoaderRoute: typeof AuthenticatedLearningCentersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/tests': {
      id: '/_authenticated/tests/tests'
      path: '/tests/tests'
      fullPath: '/tests/tests'
      preLoaderRoute: typeof AuthenticatedTestsTestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/questions': {
      id: '/_authenticated/tests/questions'
      path: '/tests/questions'
      fullPath: '/tests/questions'
      preLoaderRoute: typeof AuthenticatedTestsQuestionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/modules': {
      id: '/_authenticated/tests/modules'
      path: '/tests/modules'
      fullPath: '/tests/modules'
      preLoaderRoute: typeof AuthenticatedTestsModulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/words': {
      id: '/_authenticated/content/words'
      path: '/content/words'
      fullPath: '/content/words'
      preLoaderRoute: typeof AuthenticatedContentWordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/lessons': {
      id: '/_authenticated/content/lessons'
      path: '/content/lessons'
      fullPath: '/content/lessons'
      preLoaderRoute: typeof AuthenticatedContentLessonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content/courses': {
      id: '/_authenticated/content/courses'
      path: '/content/courses'
      fullPath: '/content/courses'
      preLoaderRoute: typeof AuthenticatedContentCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tests/questions/create': {
      id: '/_authenticated/tests/questions/create'
      path: '/create'
      fullPath: '/tests/questions/create'
      preLoaderRoute: typeof AuthenticatedTestsQuestionsCreateRouteImport
      parentRoute: typeof AuthenticatedTestsQuestionsRoute
    }
  }
}

interface AuthenticatedTestsQuestionsRouteChildren {
  AuthenticatedTestsQuestionsCreateRoute: typeof AuthenticatedTestsQuestionsCreateRoute
}

const AuthenticatedTestsQuestionsRouteChildren: AuthenticatedTestsQuestionsRouteChildren =
  {
    AuthenticatedTestsQuestionsCreateRoute:
      AuthenticatedTestsQuestionsCreateRoute,
  }

const AuthenticatedTestsQuestionsRouteWithChildren =
  AuthenticatedTestsQuestionsRoute._addFileChildren(
    AuthenticatedTestsQuestionsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedLearningCentersRoute: typeof AuthenticatedLearningCentersRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedContentCoursesRoute: typeof AuthenticatedContentCoursesRoute
  AuthenticatedContentLessonsRoute: typeof AuthenticatedContentLessonsRoute
  AuthenticatedContentWordsRoute: typeof AuthenticatedContentWordsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedTestsModulesRoute: typeof AuthenticatedTestsModulesRoute
  AuthenticatedTestsQuestionsRoute: typeof AuthenticatedTestsQuestionsRouteWithChildren
  AuthenticatedTestsTestsRoute: typeof AuthenticatedTestsTestsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedLearningCentersRoute: AuthenticatedLearningCentersRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedContentCoursesRoute: AuthenticatedContentCoursesRoute,
  AuthenticatedContentLessonsRoute: AuthenticatedContentLessonsRoute,
  AuthenticatedContentWordsRoute: AuthenticatedContentWordsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedTestsModulesRoute: AuthenticatedTestsModulesRoute,
  AuthenticatedTestsQuestionsRoute:
    AuthenticatedTestsQuestionsRouteWithChildren,
  AuthenticatedTestsTestsRoute: AuthenticatedTestsTestsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
